### ISSUE TITLE
Can't build, unable to find "Using TS3Client"

### ISSUE THREAD

**Issue by DatDraggy** [Kleberstoff/TeamSpeak-FCKCS#1]
I wanted to play around it too but I can't build it because TS3Client is missing. 

I guess the TS3Client library(idk what its called) is not in the github repo?
How do I get it?

**Comment by Kleberstoff** [comment]
I compiled the TS3Client Repo myself from Splamys Github, as "mentioned" in the Credits.

https://github.com/Splamy/TS3AudioBot/tree/master/TS3Client

Hope this clears everything up.

**Comment by DatDraggy** [comment]
Okay after a looot of time trying to add that stuff I finally got it working xD
I really struggled with all the things TS3Client needed lol

Thanks xP
